### ISSUE TITLE
How to find all css selectors about ibus?

### ISSUE THREAD

**Issue by tmltmltml** [tuberry/ibus-tweaker#7]
Hello, @tuberry ! Sorry to bother you again.

I want to find what css selectors in ibus are equal to the configurations about rime color scheme which can be conviniently 
  edited on  [Rime 西米](https://bennyyip.github.io/Rime-See-Me/) . E.g., which selector is equal to `comment_text_color`.

However, both of `GtkInspector` and `look-glass` couldn't help me find css selectors (or I couldn't use them rightly?). 
Nor can I find a reference manual.

I'd appreciate it if you could share how you find these selectors like `.candidate-popup-text`.

**Comment by tuberry** [comment]
You're welcome. All of them can be found easily in gnome shell's [repo](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/ibusCandidatePopup.js) or the [simplified](https://github.com/tuberry/ibus-tweaker/blob/master/ibus-tweaker%40tuberry.github.com/extension.js#L201) version, but the selectors may not match every part you want separately so that you might not achieve rime's color scheme perfectly in CSS.

**Comment by tmltmltml** [comment]
Thanks for your time!
I will explore them. And in case of other quesions, I will close this issue later.

**Comment by tmltmltml** [comment]
Wish you all the best!
